-- MySQL Script generated by MySQL Workbench
-- Wed Jun  5 13:15:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema database_mapper_mysql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database_mapper_mysql` DEFAULT CHARACTER SET utf8 ;
USE `database_mapper_mysql` ;

-- -----------------------------------------------------
-- Table `database_mapper_mysql`.`variations_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_mapper_mysql`.`variations_table` (
  `id_variations_table` BIGINT NOT NULL AUTO_INCREMENT,
  `not_null_col` VARCHAR(10) NOT NULL,
  `unique_col` VARCHAR(20) NULL,
  `binary_col` VARCHAR(30) BINARY NULL,
  `unsigned_col` INT UNSIGNED NULL,
  `generated_col` VARCHAR(40) GENERATED ALWAYS AS (CONCAT(not_null_col, '-', unique_col)) VIRTUAL,
  `default_expression_bool_column` TINYINT(1) NULL DEFAULT 1,
  `not_null_unique_col` VARCHAR(50) NOT NULL,
  `not_null_binary_col` VARCHAR(60) BINARY NOT NULL,
  `not_null_unsigned_col` INT UNSIGNED NOT NULL,
  `not_null_auto_generated_col` INT GENERATED ALWAYS AS (not_null_unsigned_col + 1) VIRTUAL,
  `not_null_unique_binary_col` VARCHAR(70) BINARY NOT NULL,
  `not_null_unique_unsigned_col` INT UNSIGNED NOT NULL,
  `not_null_unique_generated_col` VARCHAR(80) GENERATED ALWAYS AS (UPPER(not_null_unique_col)) VIRTUAL,
  `not_null_unique_binary_generated_col` VARCHAR(90) GENERATED ALWAYS AS (LOWER(not_null_unique_binary_col)) VIRTUAL,
  `not_null_unique_binary_generated_default_value_col` VARCHAR(100) NULL DEFAULT 'DEFAULT',
  `unique_binary_col` VARCHAR(200) BINARY NULL,
  `unique_unsigned_col` INT UNSIGNED NULL,
  `unique_generated_col` VARCHAR(400) GENERATED ALWAYS AS (REVERSE(unique_col)) VIRTUAL,
  `binary_generated_col` VARCHAR(500) GENERATED ALWAYS AS (BINARY unique_binary_col) VIRTUAL,
  `datetime_default_value` DATETIME NULL DEFAULT '1970-01-01 00:00:00',
  PRIMARY KEY (`id_variations_table`),
  UNIQUE INDEX `unique_col_UNIQUE` (`unique_col` ASC) VISIBLE,
  UNIQUE INDEX `not_null_unique_col_UNIQUE` (`not_null_unique_col` ASC) VISIBLE,
  UNIQUE INDEX `not_null_unique_binary_col_UNIQUE` (`not_null_unique_binary_col` ASC) VISIBLE,
  UNIQUE INDEX `not_null_unique_unsigned_col_UNIQUE` (`not_null_unique_unsigned_col` ASC) VISIBLE,
  UNIQUE INDEX `not_null_unique_generated_col_UNIQUE` (`not_null_unique_generated_col` ASC) VISIBLE,
  UNIQUE INDEX `not_null_unique_binary_unsigned_col_UNIQUE` (`not_null_unique_binary_generated_col` ASC) VISIBLE,
  UNIQUE INDEX `unique_binary_col_UNIQUE` (`unique_binary_col` ASC) VISIBLE,
  UNIQUE INDEX `unique_unsigned_col_UNIQUE` (`unique_unsigned_col` ASC) VISIBLE,
  UNIQUE INDEX `unique_generated_col_UNIQUE` (`unique_generated_col` ASC) VISIBLE)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `database_mapper_mysql`.`string_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_mapper_mysql`.`string_table` (
  `id_string_table` CHAR(36) NOT NULL,
  `char_col` CHAR(36) NULL,
  `varchar_col` VARCHAR(100) NULL,
  `binary_col` BINARY NULL,
  `varbinary_col` VARBINARY(1000) NULL,
  `blob_col` BLOB NULL,
  `text_col` TEXT NULL,
  `enum_col` ENUM('enum1', 'enum2') NULL,
  `set_col` SET('set1', 'set2') NULL,
  `variations_table_id` BIGINT NOT NULL,
  PRIMARY KEY (`id_string_table`),
  INDEX `fk_string_table_variations_table_idx` (`variations_table_id` ASC) VISIBLE,
  UNIQUE INDEX `char_col_UNIQUE` (`char_col` ASC) VISIBLE,
  UNIQUE INDEX `varchar_col_UNIQUE` (`varchar_col` ASC) VISIBLE,
  UNIQUE INDEX `binary_col_UNIQUE` (`binary_col` ASC) VISIBLE,
  UNIQUE INDEX `varbinary_col_UNIQUE` (`varbinary_col` ASC) VISIBLE,
  UNIQUE INDEX `blob_col_UNIQUE` (`blob_col`(191) ASC) VISIBLE,
  UNIQUE INDEX `text_col_UNIQUE` (`text_col`(191) ASC) VISIBLE,
  UNIQUE INDEX `enum_col_UNIQUE` (`enum_col` ASC) VISIBLE,
  UNIQUE INDEX `set_col_UNIQUE` (`set_col` ASC) VISIBLE,
  CONSTRAINT `fk_string_table_variations_table`
    FOREIGN KEY (`variations_table_id`)
    REFERENCES `database_mapper_mysql`.`variations_table` (`id_variations_table`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_mapper_mysql`.`numeric_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_mapper_mysql`.`numeric_table` (
  `id_numeric_table` BIGINT NOT NULL,
  `int_col` INT UNSIGNED NULL,
  `mediumint_col` MEDIUMINT UNSIGNED NULL,
  `smallint_col` SMALLINT NULL,
  `tinyint_col` TINYINT UNSIGNED NULL,
  `bool_col` TINYINT(1) UNSIGNED NULL,
  `decimal_col` DECIMAL NULL,
  `decimal_variable_col` DECIMAL(13,2) UNSIGNED NULL,
  `float_col` FLOAT UNSIGNED NULL,
  `float_variable_col` FLOAT(3,3) NULL,
  `real_col` REAL UNSIGNED NULL,
  `double_col` DOUBLE UNSIGNED NULL,
  `numeric_col` NUMERIC NULL,
  `bit_col` BIT NULL,
  `variations_table_id` BIGINT NOT NULL,
  PRIMARY KEY (`id_numeric_table`),
  INDEX `fk_numeric_table_variations_table1_idx` (`variations_table_id` ASC) VISIBLE,
  CONSTRAINT `fk_numeric_table_variations_table1`
    FOREIGN KEY (`variations_table_id`)
    REFERENCES `database_mapper_mysql`.`variations_table` (`id_variations_table`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_mapper_mysql`.`date_and_time_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_mapper_mysql`.`date_and_time_table` (
  `id_date_and_time_table` CHAR(36) NOT NULL,
  `date_col` DATE NULL,
  `time_col` TIME NULL,
  `datetime_col` DATETIME NULL,
  `timestamp_col` TIMESTAMP NULL,
  `year_col` YEAR NULL,
  `variations_table_id` BIGINT NULL,
  `numeric_table_id` BIGINT NOT NULL,
  PRIMARY KEY (`id_date_and_time_table`),
  INDEX `fk_date_and_time_table_variations_table1_idx` (`variations_table_id` ASC) VISIBLE,
  INDEX `fk_date_and_time_table_numeric_table1_idx` (`numeric_table_id` ASC) VISIBLE,
  CONSTRAINT `fk_date_and_time_table_variations_table1`
    FOREIGN KEY (`variations_table_id`)
    REFERENCES `database_mapper_mysql`.`variations_table` (`id_variations_table`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_date_and_time_table_numeric_table1`
    FOREIGN KEY (`numeric_table_id`)
    REFERENCES `database_mapper_mysql`.`numeric_table` (`id_numeric_table`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_mapper_mysql`.`spatial_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_mapper_mysql`.`spatial_table` (
  `id_spatial_table` CHAR(36) NOT NULL,
  `linestring` LINESTRING NOT NULL,
  `geometry` GEOMETRY NOT NULL,
  `geometrycollection` GEOMETRYCOLLECTION NOT NULL,
  `point` POINT NOT NULL,
  `polygon` POLYGON NOT NULL,
  `multipoint` MULTIPOINT NOT NULL,
  `multipolygon` MULTIPOLYGON NOT NULL,
  `multilinestring` MULTILINESTRING NOT NULL,
  `variations_table_id` BIGINT NOT NULL,
  PRIMARY KEY (`id_spatial_table`),
  INDEX `fk_spatial_table_variations_table1_idx` (`variations_table_id` ASC) VISIBLE,
  CONSTRAINT `fk_spatial_table_variations_table1`
    FOREIGN KEY (`variations_table_id`)
    REFERENCES `database_mapper_mysql`.`variations_table` (`id_variations_table`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_mapper_mysql`.`json_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_mapper_mysql`.`json_table` (
  `id_json_table` CHAR(36) NOT NULL,
  `json_not_nullable_col` JSON NOT NULL,
  `json_unique_col` JSON NULL,
  `json_not_nullable_unique_col` JSON NOT NULL,
  `json_generated_column` JSON GENERATED ALWAYS AS (JSON_OBJECT('key', JSON_EXTRACT(json_not_nullable_col, '$.key'))) VIRTUAL,
  `json_not_nullable_generated_col` JSON GENERATED ALWAYS AS (JSON_ARRAY_APPEND(json_not_nullable_unique_col, '$', 'new_value')) VIRTUAL,
  `json_unique_generated_col` JSON GENERATED ALWAYS AS (JSON_MERGE_PATCH(json_unique_col, JSON_OBJECT('new_key', 'new_value'))) VIRTUAL,
  `json_not_nullable_unique_col_index` VARCHAR(191) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(json_not_nullable_unique_col, '$.address.city'))) VIRTUAL,
  `json_unique_generated_col_index` VARCHAR(191) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(json_unique_generated_col, '$.specific_path'))) VIRTUAL,
  `variations_table_id` BIGINT NOT NULL,
  `string_table_id` CHAR(36) NULL,
  `spatial_table_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`id_json_table`),
  UNIQUE INDEX `json_not_nullable_unique_col_UNIQUE` (`json_not_nullable_unique_col_index` ASC) VISIBLE,
  UNIQUE INDEX `json_unique_generated_col_UNIQUE` (`json_unique_generated_col_index` ASC) VISIBLE,
  INDEX `fk_json_table_variations_table1_idx` (`variations_table_id` ASC) VISIBLE,
  INDEX `fk_json_table_string_table1_idx` (`string_table_id` ASC) VISIBLE,
  INDEX `fk_json_table_spatial_table1_idx` (`spatial_table_id` ASC) VISIBLE,
  CONSTRAINT `fk_json_table_variations_table1`
    FOREIGN KEY (`variations_table_id`)
    REFERENCES `database_mapper_mysql`.`variations_table` (`id_variations_table`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_json_table_string_table1`
    FOREIGN KEY (`string_table_id`)
    REFERENCES `database_mapper_mysql`.`string_table` (`id_string_table`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_json_table_spatial_table1`
    FOREIGN KEY (`spatial_table_id`)
    REFERENCES `database_mapper_mysql`.`spatial_table` (`id_spatial_table`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;





-- -----------------------------------------------------
-- Table `database_mapper_mysql`.`no_id_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_mapper_mysql`.`no_id_table` (
  `name` VARCHAR(100) NULL,
  `gender` VARCHAR(20) NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
